services:
  - type: web
    name: crop-recommendation-app
    env: python
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.11"
